[project]
name = "ai-orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Kelby Madal-Hellmuth", email = "kelby0320@gmail.com" }]
requires-python = ">=3.14"
dependencies = [
    "anyio>=4.11.0",
    "fastapi>=0.121.2",
    "grpcio>=1.76.0",
    "grpcio-tools>=1.76.0",
    "httpx>=0.28.1",
    "uvicorn>=0.38.0",
]

[project.scripts]
ai-orchestrator = "ai_orchestrator:main"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = [
    "pytest-asyncio>=1.3.0",
    "types-grpcio>=1.0.0.20251009",
    "types-protobuf>=6.32.1.20251210",
    "mypy-protobuf>=3.6.0",
]
