[project]
name = "ai-orchestrator"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [{ name = "Kelby Madal-Hellmuth", email = "kelby0320@gmail.com" }]
requires-python = ">=3.14"
dependencies = ["fastapi>=0.121.2", "httpx>=0.28.1", "uvicorn>=0.38.0"]

[project.scripts]
ai-orchestrator = "ai_orchestrator:main"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[dependency-groups]
dev = ["anyio>=4.11.0", "pytest>=9.0.1", "trio>=0.32.0"]
