[project]
name = "ai-infra"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Kelby Madal-Hellmuth", email = "kelby0320@gmail.com" }
]
requires-python = ">=3.14"
dependencies = [
    "ai-core",
    "alembic>=1.17.2",
    "httpx>=0.28.1",
    "psycopg[binary]>=3.3.2",
    "pydantic-settings>=2.12.0",
    "sqlalchemy>=2.0.45",
]

[project.scripts]
ai-infra = "ai_infra:main"

[build-system]
requires = ["uv_build>=0.9.8,<0.10.0"]
build-backend = "uv_build"

[tool.uv.sources]
ai-core = { workspace = true }
